import { Battery, Bluetooth, Box, Droplets, Radio, Thermometer } from 'lucide-react'
import { SectionIntro } from '../components/ui/SectionIntro'
import { SensorNode } from '../components/visuals/SensorNode'

const specs = [
  ['Measurements','Optical pulse / SpO₂ / perfusion trend'],['Ingress target','IP67 — design target, not validated'],['Runtime target','24+ hours at nominal sampling profile'],['Local storage','Encrypted rolling observation buffer'],['Feedback','Status ring / vibration / single control'],['Attachment','Replaceable woven strap / adhesive carrier study'],
]

export function HardwarePage() {
  return <main className="inner-page hardware-page">
    <section className="hardware-hero"><div className="hardware-hero__copy"><p>NODE ONE / INDUSTRIAL DESIGN STUDY 02</p><h1>A patient node<br/>with one job.</h1><span>Collect useful trends. Report its own limits. Stay out of the way.</span></div><div className="hardware-hero__object"><SensorNode/><div className="dimension dimension--h">54 mm</div><div className="dimension dimension--v">14.8 mm</div></div><div className="hardware-hero__note">NON-FUNCTIONAL FORM STUDY<br/>DIMENSIONS ARE PROVISIONAL</div></section>
    <nav className="jump-nav"><span>Node One</span><a href="#intent">Design intent</a><a href="#anatomy">Anatomy</a><a href="#specification">Specification</a><a href="#kit">System kit</a></nav>
    <section className="content-section hardware-intent" id="intent"><SectionIntro index="01" eyebrow="Design intent" title="Readable by touch. Quiet by default." body="The enclosure study avoids a touchscreen, exposed ports and decorative lighting. Feedback is limited to the conditions an operator can act on."/><div className="intent-grid">{[[Droplets,'Sealed surfaces','A continuous housing geometry for cleaning and weather exposure.'],[Battery,'Power legibility','Remaining runtime is visible from Field Tab and on-node when requested.'],[Thermometer,'Contact awareness','Placement quality is treated as a first-class system state.'],[Bluetooth,'Local pairing','A short, deliberate pairing sequence reduces accidental reassignment.']].map(([Icon,t,b])=><article key={t}><Icon/><h3>{t}</h3><p>{b}</p></article>)}</div></section>
    <section className="exploded-section" id="anatomy"><div className="exploded-section__intro"><span>02 / PHYSICAL ARCHITECTURE</span><h2>A replaceable carrier around a sealed core.</h2><p>This exploded view is a design hypothesis for engineering review, not a released construction.</p></div><div className="exploded"><div className="exploded-part part-1"><span>01</span><i/>Optical window</div><div className="exploded-part part-2"><span>02</span><i/>Sealed sensor core</div><div className="exploded-part part-3"><span>03</span><i/>Tactile status ring</div><div className="exploded-part part-4"><span>04</span><i/>Replaceable carrier</div><div className="exploded-part part-5"><span>05</span><i/>Woven strap</div></div></section>
    <section className="content-section specification" id="specification"><SectionIntro index="03" eyebrow="Preliminary specification" title="Targets, not marketing claims."/><div className="spec-table">{specs.map((s,i)=><div key={s[0]}><span>{String(i+1).padStart(2,'0')}</span><b>{s[0]}</b><p>{s[1]}</p></div>)}</div><p className="spec-note">All values are provisional engineering targets. No performance, safety, ingress, runtime or accuracy claim has been validated.</p></section>
    <section className="kit-section" id="kit"><SectionIntro index="04" eyebrow="System kit" title="Pack only what the workflow needs." inverse/><div className="kit-grid"><article><SensorNode compact/><span>06 ×</span><h3>Patient nodes</h3></article><article><div className="kit-relay"><Radio/><b>R1</b></div><span>01 ×</span><h3>Local relay</h3></article><article><div className="kit-case"><Box/><i/><i/><i/></div><span>01 ×</span><h3>Charging case</h3></article></div></section>
  </main>
}
